### ISSUE TITLE
fyi alt research from the stan group for benching ppls

### ISSUE THREAD

**Issue by SteveBronder** [facebookresearch/pplbench#47]
Hello! fyi Stan also has a benchmark library we are working on to compare PPL performance across different models. Right now it's focus is Stan, but the tf prob and turing folks are also having a look at it. It feels like the goals are v similar here, may be good to put heads together!

https://github.com/MansMeg/posteriordb

**Comment by nimar** [comment]
Agreed!! Please check your email for an invite to a discussion on this with other interested folks.
