### ISSUE TITLE
cannot run examples

### ISSUE THREAD

**Issue by enguang2** [facebookresearch/pplbench#62]
### Issue Description
`usage: pplbench [-h] [--print_config [skip_null]] config
pplbench: error: Parser key "config": 'examples/example.json' is not of type 'object'

Failed validating 'type' in schema:
    {'additionalProperties': False,
     'properties': {'figures': {'additionalProperties': False,
                                'properties': {'generate_pll': {'type': 'boolean'},
                                               'suffix': {'type': 'string'}},
                                'type': 'object'},
                    'loglevels': {'additionalProperties': {'enum': ['DEBUG',
                                                                    'INFO',
                                                                    'WARNING',
                                                                    'ERROR',
                                                                    'CRITICAL'],
                                                           'type': 'string'},
                                  'type': 'object'},
                    'model': {'additionalProperties': False,
                              'properties': {'args': {'additionalProperties': True,
                                                      'properties': {'k': {'minimum': 1,
                                                                           'type': 'integer'},
                                                                     'n': {'minimum': 2,
                                                                           'type': 'integer'}},
                                                      'propertyNames': {'pattern': '^[A-Za-z_][A-Za-z0-9_]*$'},
                                                      'required': ['n'],
                                                      'type': 'object'},
                                             'class': {'type': 'string'},
                                             'package': {'type': 'string'},
                                             'seed': {'minimum': 1,
                                                      'type': 'integer'}},
                              'required': ['class'],
                              'type': 'object'},
                    'num_samples': {'minimum': 1, 'type': 'integer'},
                    'output_root_dir': {'type': 'string'},
                    'ppls': {'items': {'additionalProperties': False,
                                       'properties': {'inference': {'additionalProperties': False,
                                                                    'properties': {'class': {'type': 'string'},
                                                                                   'compile_args': {'additionalProperties': True,
                                                                                                    'propertyNames': {'pattern': '^[A-Za-z_][A-Za-z0-9_]*$'},
                                                                                                    'type': 'object'},
                                                                                   'infer_args': {'additionalProperties': True,
                                                                                                  'propertyNames': {'pattern': '^[A-Za-z_][A-Za-z0-9_]*$'},
                                                                                                  'type': 'object'}},
                                                                    'required': ['class'],
                                                                    'type': 'object'},
                                                      'legend': {'properties': {'color': {'type': 'string'},
                                                                                'name': {'type': 'string'}},
                                                                 'type': 'object'},
                                                      'name': {'type': 'string'},
                                                      'package': {'type': 'string'},
                                                      'seed': {'minimum': 1,
                                                               'type': 'integer'}},
                                       'required': ['name', 'inference'],
                                       'type': 'object'},
                             'type': 'array'},
                    'save_samples': {'type': 'boolean'},
                    'trials': {'minimum': 2, 'type': 'integer'}},
     'required': ['model', 'ppls', 'num_samples', 'trials'],
     'type': 'object'}

On instance:
    'examples/example.json'`

### Steps to Reproduce
I successfully install pystan and pplbench but it will crash for `pplbench examples/example.json
`

### System Info
Please provide information about your setup
- PyTorch Version (run `print(torch.__version__)` 
- Python version 3.7.9

**Comment by horizon-blue** [comment]
Hello @enguang2, the argument that PPL Bench expects is actually a *path* to a JSON configuration file.

If you're installing with `pip`, you can copy-paste any of the configuration files from our [examples](https://github.com/facebookresearch/pplbench/tree/master/examples/) directory, store it to your own machine, and run `pplbench` with the file name as the argument. (Our [home page](https://pplbench.org/) probably explains the usage a bit better :).

If you're installing from source code and already has a copy of the repository on your own machine, just `cd` into the root directory of our project and make sure that `examples/example.json` is the right path to an actual file.
